services:
  java-book-library-api:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    image: java-book-library
    container_name: java-book-library-api
    env_file: .env
    links:
      - postgresql

  postgresql:
    image: 'postgres:latest'
    container_name: java-book-library-postgresql
    environment:
      - 'POSTGRES_DB=librarydb'
      - 'POSTGRES_PASSWORD=challenge'
      - 'POSTGRES_USER=challenge'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - '../volumes/postgresql/log:/var/log/postgresql'
